"""drop_group_code

Revision ID: 450c3f059755
Revises: e8b4f2a912c0
Create Date: 2026-09-03 07:58:23.013984

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '450c3f059755'
down_revision: Union[str, None] = 'e8b4f2a912c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('code'), table_name='customer_groups')
    op.drop_column('customer_groups', 'code')
    op.alter_column('customers', 'region_id',
               existing_type=mysql.BIGINT(),
               comment='注册地行政区域',
               existing_comment='行政区域',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('customers', 'region_id',
               existing_type=mysql.BIGINT(),
               comment='行政区域',
               existing_comment='注册地行政区域',
               existing_nullable=True)
    op.add_column('customer_groups', sa.Column('code', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=32), nullable=False))
    op.create_index(op.f('code'), 'customer_groups', ['code'], unique=True)
    # ### end Alembic commands ###
