"""warrant_draft drop denomination draft_type

Revision ID: 966f1847e45f
Revises: 8ebb29be728a
Create Date: 2026-09-02 12:52:49.165330

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '966f1847e45f'
down_revision: Union[str, None] = '8ebb29be728a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('warrant_drafts', 'draft_type')
    op.drop_column('warrant_drafts', 'denomination')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('warrant_drafts', sa.Column('denomination', mysql.DECIMAL(precision=18, scale=2), nullable=False, comment='票面总额'))
    op.add_column('warrant_drafts', sa.Column('draft_type', mysql.SMALLINT(), autoincrement=False, nullable=False, comment='10商业承兑20银行承兑30支票'))
    # ### end Alembic commands ###
