"""warrant_house_ground_region

Revision ID: 8254f71a7920
Revises: 4ab10f2aa35e
Create Date: 2026-08-31 17:56:46.753072

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '8254f71a7920'
down_revision: Union[str, None] = '4ab10f2aa35e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('warrant_grounds', sa.Column('region_id', sa.BigInteger(), nullable=True, comment='行政区域（方便按区域统计）'))
    op.alter_column('warrant_grounds', 'ground_locate',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255),
               comment='详细地址',
               existing_nullable=False)
    op.create_index(op.f('ix_warrant_grounds_region_id'), 'warrant_grounds', ['region_id'], unique=False)
    op.create_foreign_key(None, 'warrant_grounds', 'user_regions', ['region_id'], ['id'], ondelete='SET NULL')
    op.add_column('warrant_houses', sa.Column('region_id', sa.BigInteger(), nullable=True, comment='行政区域（方便按区域统计）'))
    op.alter_column('warrant_houses', 'house_locate',
               existing_type=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_unicode_ci', length=255),
               comment='详细地址（换证后同坐落可能出现多套证，不唯一）',
               existing_comment='坐落（换证后同坐落可能出现多套证，不唯一）',
               existing_nullable=False)
    op.create_index(op.f('ix_warrant_houses_region_id'), 'warrant_houses', ['region_id'], unique=False)
    op.create_foreign_key(None, 'warrant_houses', 'user_regions', ['region_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'warrant_houses', type_='foreignkey')
    op.drop_index(op.f('ix_warrant_houses_region_id'), table_name='warrant_houses')
    op.alter_column('warrant_houses', 'house_locate',
               existing_type=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_unicode_ci', length=255),
               comment='坐落（换证后同坐落可能出现多套证，不唯一）',
               existing_comment='详细地址（换证后同坐落可能出现多套证，不唯一）',
               existing_nullable=False)
    op.drop_column('warrant_houses', 'region_id')
    op.drop_constraint(None, 'warrant_grounds', type_='foreignkey')
    op.drop_index(op.f('ix_warrant_grounds_region_id'), table_name='warrant_grounds')
    op.alter_column('warrant_grounds', 'ground_locate',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255),
               comment=None,
               existing_comment='详细地址',
               existing_nullable=False)
    op.drop_column('warrant_grounds', 'region_id')
    # ### end Alembic commands ###
