"""article: drop repay_method, add credit_term_unit, update credit_term default

Revision ID: 52fdfbcf8757
Revises: dc5399375112
Create Date: 2026-09-11 09:28:03.086125

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '52fdfbcf8757'
down_revision: Union[str, None] = 'dc5399375112'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('credit_term_unit', sa.SmallInteger(), nullable=False, comment='期限单位 10年 20月 30天'))
    op.alter_column('articles', 'credit_term',
               existing_type=mysql.SMALLINT(),
               comment='授信期限',
               existing_comment='授信期限(月)',
               existing_nullable=False)
    op.drop_column('articles', 'repay_method')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('repay_method', mysql.SMALLINT(), autoincrement=False, nullable=True, comment='还款方式'))
    op.alter_column('articles', 'credit_term',
               existing_type=mysql.SMALLINT(),
               comment='授信期限(月)',
               existing_comment='授信期限',
               existing_nullable=False)
    op.drop_column('articles', 'credit_term_unit')
    # ### end Alembic commands ###
