"""warrant add remark

Revision ID: f94b64599896
Revises: 966f1847e45f
Create Date: 2026-09-02 13:02:51.957217

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f94b64599896'
down_revision: Union[str, None] = '966f1847e45f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('warrants', sa.Column('remark', sa.String(length=128), nullable=True, comment='备注'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('warrants', 'remark')
    # ### end Alembic commands ###
