"""drop extra tag status

Revision ID: bbaf5aaf8416
Revises: d908b63105e9
Create Date: 2026-08-29 23:03:07.818685

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'bbaf5aaf8416'
down_revision: Union[str, None] = 'd908b63105e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customer_extra_tags', 'status')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customer_extra_tags', sa.Column('status', mysql.SMALLINT(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
