"""approval_stage

Revision ID: 0e9880fcaf6d
Revises: 8f84a6f42726
Create Date: 2026-09-10 18:02:11.094056

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '0e9880fcaf6d'
down_revision: Union[str, None] = '8f84a6f42726'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('approval_flow_nodes', sa.Column('stage', sa.SmallInteger(), nullable=False, comment='阶段号，stage 之间顺序推进，同 stage 内节点并行'))
    op.alter_column('approval_flow_nodes', 'step',
               existing_type=mysql.SMALLINT(),
               comment='节点顺序，stage 内部序号（同 stage 可并行）',
               existing_comment='节点顺序，从 1 开始',
               existing_nullable=False)
    op.add_column('approval_instances', sa.Column('current_stage', sa.SmallInteger(), nullable=False, comment='当前阶段 stage'))
    op.alter_column('approval_instances', 'current_step',
               existing_type=mysql.SMALLINT(),
               comment='当前节点 step（stage 内部序号）',
               existing_comment='当前节点 step',
               existing_nullable=False)
    op.alter_column('articles', 'renewal',
               existing_type=mysql.DECIMAL(precision=18, scale=2),
               comment='续贷金额(元)',
               existing_comment='续贷金额',
               existing_nullable=False)
    op.alter_column('articles', 'augment',
               existing_type=mysql.DECIMAL(precision=18, scale=2),
               comment='新增金额(元)',
               existing_comment='新增金额',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('articles', 'augment',
               existing_type=mysql.DECIMAL(precision=18, scale=2),
               comment='新增金额',
               existing_comment='新增金额(元)',
               existing_nullable=False)
    op.alter_column('articles', 'renewal',
               existing_type=mysql.DECIMAL(precision=18, scale=2),
               comment='续贷金额',
               existing_comment='续贷金额(元)',
               existing_nullable=False)
    op.alter_column('approval_instances', 'current_step',
               existing_type=mysql.SMALLINT(),
               comment='当前节点 step',
               existing_comment='当前节点 step（stage 内部序号）',
               existing_nullable=False)
    op.drop_column('approval_instances', 'current_stage')
    op.alter_column('approval_flow_nodes', 'step',
               existing_type=mysql.SMALLINT(),
               comment='节点顺序，从 1 开始',
               existing_comment='节点顺序，stage 内部序号（同 stage 可并行）',
               existing_nullable=False)
    op.drop_column('approval_flow_nodes', 'stage')
    # ### end Alembic commands ###
