"""unify base model audit fields

Revision ID: 08f492f00f99
Revises: 9320c152d20e
Create Date: 2026-08-29 21:13:24.503301

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '08f492f00f99'
down_revision: Union[str, None] = '9320c152d20e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('approval_flow_defs', sa.Column('created_by', sa.BigInteger(), nullable=True))
    op.add_column('approval_flow_defs', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False))
    op.create_foreign_key(None, 'approval_flow_defs', 'users', ['created_by'], ['id'])
    op.add_column('approval_flow_nodes', sa.Column('created_by', sa.BigInteger(), nullable=True))
    op.add_column('approval_flow_nodes', sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False))
    op.add_column('approval_flow_nodes', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False))
    op.create_foreign_key(None, 'approval_flow_nodes', 'users', ['created_by'], ['id'])
    op.add_column('approval_instances', sa.Column('created_by', sa.BigInteger(), nullable=True))
    op.add_column('approval_instances', sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False))
    op.add_column('approval_instances', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False))
    op.create_foreign_key(None, 'approval_instances', 'users', ['created_by'], ['id'])
    op.add_column('approval_tasks', sa.Column('created_by', sa.BigInteger(), nullable=True))
    op.add_column('approval_tasks', sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False))
    op.add_column('approval_tasks', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False))
    op.create_foreign_key(None, 'approval_tasks', 'users', ['created_by'], ['id'])
    op.add_column('attachments', sa.Column('created_by', sa.BigInteger(), nullable=True))
    op.add_column('attachments', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False))
    op.create_foreign_key(None, 'attachments', 'users', ['created_by'], ['id'])
    op.add_column('customer_company_profiles', sa.Column('created_by', sa.BigInteger(), nullable=True))
    op.add_column('customer_company_profiles', sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False))
    op.add_column('customer_company_profiles', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False))
    op.create_foreign_key(None, 'customer_company_profiles', 'users', ['created_by'], ['id'])
    op.add_column('customer_core_histories', sa.Column('created_by', sa.BigInteger(), nullable=True))
    op.add_column('customer_core_histories', sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False))
    op.create_foreign_key(None, 'customer_core_histories', 'users', ['created_by'], ['id'])
    op.add_column('customer_core_limits', sa.Column('created_by', sa.BigInteger(), nullable=True))
    op.add_column('customer_core_limits', sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False))
    op.add_column('customer_core_limits', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False))
    op.create_foreign_key(None, 'customer_core_limits', 'users', ['created_by'], ['id'])
    op.alter_column('customer_credit_regions', 'created_by',
               existing_type=mysql.BIGINT(),
               nullable=True)
    op.add_column('customer_directors', sa.Column('created_by', sa.BigInteger(), nullable=True))
    op.add_column('customer_directors', sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False))
    op.add_column('customer_directors', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False))
    op.create_foreign_key(None, 'customer_directors', 'users', ['created_by'], ['id'])
    op.add_column('customer_extends', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False))
    op.alter_column('customer_extends', 'created_by',
               existing_type=mysql.BIGINT(),
               nullable=True)
    op.alter_column('customer_extra_tags', 'created_by',
               existing_type=mysql.BIGINT(),
               nullable=True)
    op.alter_column('customer_groups', 'created_by',
               existing_type=mysql.BIGINT(),
               nullable=True)
    op.add_column('customer_industries', sa.Column('created_by', sa.BigInteger(), nullable=True))
    op.add_column('customer_industries', sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False))
    op.add_column('customer_industries', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False))
    op.create_foreign_key(None, 'customer_industries', 'users', ['created_by'], ['id'])
    op.add_column('customer_personal_profiles', sa.Column('created_by', sa.BigInteger(), nullable=True))
    op.add_column('customer_personal_profiles', sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False))
    op.add_column('customer_personal_profiles', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False))
    op.create_foreign_key(None, 'customer_personal_profiles', 'users', ['created_by'], ['id'])
    op.add_column('customer_shareholders', sa.Column('created_by', sa.BigInteger(), nullable=True))
    op.add_column('customer_shareholders', sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False))
    op.add_column('customer_shareholders', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False))
    op.create_foreign_key(None, 'customer_shareholders', 'users', ['created_by'], ['id'])
    op.add_column('customer_tag_relations', sa.Column('created_by', sa.BigInteger(), nullable=True))
    op.add_column('customer_tag_relations', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False))
    op.create_foreign_key(None, 'customer_tag_relations', 'users', ['created_by'], ['id'])
    # customers：create_by → created_by 对齐 Base 命名，RENAME 保留数据（原 FK 自动跟随列名）
    op.execute("ALTER TABLE customers RENAME COLUMN create_by TO created_by")
    op.add_column('institution_branches', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False))
    op.alter_column('institution_branches', 'created_by',
               existing_type=mysql.BIGINT(),
               nullable=True)
    op.add_column('institution_contacts', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False))
    op.alter_column('institution_contacts', 'created_by',
               existing_type=mysql.BIGINT(),
               nullable=True)
    op.alter_column('institution_credit_agreements', 'created_by',
               existing_type=mysql.BIGINT(),
               nullable=True)
    op.add_column('institution_credit_histories', sa.Column('created_by', sa.BigInteger(), nullable=True))
    op.add_column('institution_credit_histories', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False))
    op.create_foreign_key(None, 'institution_credit_histories', 'users', ['created_by'], ['id'])
    op.alter_column('institutions', 'created_by',
               existing_type=mysql.BIGINT(),
               nullable=True)
    op.add_column('user_departments', sa.Column('created_by', sa.BigInteger(), nullable=True))
    op.create_foreign_key(None, 'user_departments', 'users', ['created_by'], ['id'])
    op.add_column('user_login_logs', sa.Column('created_by', sa.BigInteger(), nullable=True))
    op.add_column('user_login_logs', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False))
    op.create_foreign_key(None, 'user_login_logs', 'users', ['created_by'], ['id'])
    op.add_column('user_menus', sa.Column('created_by', sa.BigInteger(), nullable=True))
    op.create_foreign_key(None, 'user_menus', 'users', ['created_by'], ['id'])
    op.add_column('user_operation_logs', sa.Column('created_by', sa.BigInteger(), nullable=True))
    op.add_column('user_operation_logs', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False))
    op.create_foreign_key(None, 'user_operation_logs', 'users', ['created_by'], ['id'])
    op.add_column('user_permissions', sa.Column('created_by', sa.BigInteger(), nullable=True))
    op.create_foreign_key(None, 'user_permissions', 'users', ['created_by'], ['id'])
    op.add_column('user_regions', sa.Column('created_by', sa.BigInteger(), nullable=True))
    op.add_column('user_regions', sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False))
    op.add_column('user_regions', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False))
    op.create_foreign_key(None, 'user_regions', 'users', ['created_by'], ['id'])
    # user_role_permissions：复合主键 → id 主键 + 复合唯一（一条 ALTER 原子完成，含审计列）
    # 先补 FK 支撑索引（role_id 原为复合 PK 第一列，DROP PK 前需有替代索引）
    op.execute("ALTER TABLE user_role_permissions ADD KEY ix_user_role_permissions_role_id (role_id)")
    op.execute(
        "ALTER TABLE user_role_permissions "
        "DROP PRIMARY KEY, "
        "ADD COLUMN id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY FIRST, "
        "ADD COLUMN created_by BIGINT NULL, "
        "ADD COLUMN created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, "
        "ADD COLUMN updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, "
        "ADD UNIQUE KEY uq_role_permission_pair (role_id, permission_id), "
        "ADD CONSTRAINT fk_user_role_permissions_created_by FOREIGN KEY (created_by) REFERENCES users (id)"
    )
    op.add_column('user_roles', sa.Column('created_by', sa.BigInteger(), nullable=True))
    op.create_foreign_key(None, 'user_roles', 'users', ['created_by'], ['id'])
    # user_user_roles：复合主键 → id 主键 + 复合唯一（同上）
    op.execute("ALTER TABLE user_user_roles ADD KEY ix_user_user_roles_user_id (user_id)")
    op.execute(
        "ALTER TABLE user_user_roles "
        "DROP PRIMARY KEY, "
        "ADD COLUMN id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY FIRST, "
        "ADD COLUMN created_by BIGINT NULL, "
        "ADD COLUMN created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, "
        "ADD COLUMN updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, "
        "ADD UNIQUE KEY uq_user_role_pair (user_id, role_id), "
        "ADD CONSTRAINT fk_user_user_roles_created_by FOREIGN KEY (created_by) REFERENCES users (id)"
    )
    op.add_column('users', sa.Column('created_by', sa.BigInteger(), nullable=True))
    op.create_foreign_key(None, 'users', 'users', ['created_by'], ['id'])
    op.alter_column('warrant_chattels', 'created_by',
               existing_type=mysql.BIGINT(),
               nullable=True)
    op.alter_column('warrant_constructions', 'created_by',
               existing_type=mysql.BIGINT(),
               nullable=True)
    op.alter_column('warrant_draft_extends', 'created_by',
               existing_type=mysql.BIGINT(),
               nullable=True)
    op.alter_column('warrant_drafts', 'created_by',
               existing_type=mysql.BIGINT(),
               nullable=True)
    op.alter_column('warrant_evaluate_companies', 'created_by',
               existing_type=mysql.BIGINT(),
               nullable=True)
    op.alter_column('warrant_evaluate_rechecks', 'created_by',
               existing_type=mysql.BIGINT(),
               nullable=True)
    op.alter_column('warrant_evaluates', 'created_by',
               existing_type=mysql.BIGINT(),
               nullable=True)
    op.alter_column('warrant_grounds', 'created_by',
               existing_type=mysql.BIGINT(),
               nullable=True)
    op.add_column('warrant_house_apps', sa.Column('created_by', sa.BigInteger(), nullable=True))
    op.create_foreign_key(None, 'warrant_house_apps', 'users', ['created_by'], ['id'])
    op.alter_column('warrant_houses', 'created_by',
               existing_type=mysql.BIGINT(),
               nullable=True)
    op.alter_column('warrant_others', 'created_by',
               existing_type=mysql.BIGINT(),
               nullable=True)
    op.alter_column('warrant_ownerships', 'created_by',
               existing_type=mysql.BIGINT(),
               nullable=True)
    op.alter_column('warrant_patents', 'created_by',
               existing_type=mysql.BIGINT(),
               nullable=True)
    op.alter_column('warrant_receivables', 'created_by',
               existing_type=mysql.BIGINT(),
               nullable=True)
    op.alter_column('warrant_receive_extends', 'created_by',
               existing_type=mysql.BIGINT(),
               nullable=True)
    op.alter_column('warrant_softwares', 'created_by',
               existing_type=mysql.BIGINT(),
               nullable=True)
    op.alter_column('warrant_stocks', 'created_by',
               existing_type=mysql.BIGINT(),
               nullable=True)
    op.add_column('warrant_storages', sa.Column('created_by', sa.BigInteger(), nullable=True))
    op.create_foreign_key(None, 'warrant_storages', 'users', ['created_by'], ['id'])
    op.alter_column('warrant_vehicles', 'created_by',
               existing_type=mysql.BIGINT(),
               nullable=True)
    op.alter_column('warrants', 'created_by',
               existing_type=mysql.BIGINT(),
               nullable=True)
    # 注：ix_warrants_created_by 为 FK 支撑索引（MySQL 1553 不可删），保留；
    # 模型 Warrant.created_by 覆写声明 index=True 与之对齐
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('warrants', 'created_by',
               existing_type=mysql.BIGINT(),
               nullable=False)
    op.alter_column('warrant_vehicles', 'created_by',
               existing_type=mysql.BIGINT(),
               nullable=False)
    op.drop_constraint(None, 'warrant_storages', type_='foreignkey')
    op.drop_column('warrant_storages', 'created_by')
    op.alter_column('warrant_stocks', 'created_by',
               existing_type=mysql.BIGINT(),
               nullable=False)
    op.alter_column('warrant_softwares', 'created_by',
               existing_type=mysql.BIGINT(),
               nullable=False)
    op.alter_column('warrant_receive_extends', 'created_by',
               existing_type=mysql.BIGINT(),
               nullable=False)
    op.alter_column('warrant_receivables', 'created_by',
               existing_type=mysql.BIGINT(),
               nullable=False)
    op.alter_column('warrant_patents', 'created_by',
               existing_type=mysql.BIGINT(),
               nullable=False)
    op.alter_column('warrant_ownerships', 'created_by',
               existing_type=mysql.BIGINT(),
               nullable=False)
    op.alter_column('warrant_others', 'created_by',
               existing_type=mysql.BIGINT(),
               nullable=False)
    op.alter_column('warrant_houses', 'created_by',
               existing_type=mysql.BIGINT(),
               nullable=False)
    op.drop_constraint(None, 'warrant_house_apps', type_='foreignkey')
    op.drop_column('warrant_house_apps', 'created_by')
    op.alter_column('warrant_grounds', 'created_by',
               existing_type=mysql.BIGINT(),
               nullable=False)
    op.alter_column('warrant_evaluates', 'created_by',
               existing_type=mysql.BIGINT(),
               nullable=False)
    op.alter_column('warrant_evaluate_rechecks', 'created_by',
               existing_type=mysql.BIGINT(),
               nullable=False)
    op.alter_column('warrant_evaluate_companies', 'created_by',
               existing_type=mysql.BIGINT(),
               nullable=False)
    op.alter_column('warrant_drafts', 'created_by',
               existing_type=mysql.BIGINT(),
               nullable=False)
    op.alter_column('warrant_draft_extends', 'created_by',
               existing_type=mysql.BIGINT(),
               nullable=False)
    op.alter_column('warrant_constructions', 'created_by',
               existing_type=mysql.BIGINT(),
               nullable=False)
    op.alter_column('warrant_chattels', 'created_by',
               existing_type=mysql.BIGINT(),
               nullable=False)
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'created_by')
    # 中间表逆操作：恢复复合主键
    op.execute(
        "ALTER TABLE user_user_roles "
        "DROP FOREIGN KEY fk_user_user_roles_created_by, "
        "DROP KEY uq_user_role_pair, DROP KEY ix_user_user_roles_user_id, "
        "DROP COLUMN created_by, DROP COLUMN created_at, DROP COLUMN updated_at, "
        "DROP COLUMN id, DROP PRIMARY KEY, ADD PRIMARY KEY (user_id, role_id)"
    )
    op.drop_constraint(None, 'user_roles', type_='foreignkey')
    op.drop_column('user_roles', 'created_by')
    op.execute(
        "ALTER TABLE user_role_permissions "
        "DROP FOREIGN KEY fk_user_role_permissions_created_by, "
        "DROP KEY uq_role_permission_pair, DROP KEY ix_user_role_permissions_role_id, "
        "DROP COLUMN created_by, DROP COLUMN created_at, DROP COLUMN updated_at, "
        "DROP COLUMN id, DROP PRIMARY KEY, ADD PRIMARY KEY (role_id, permission_id)"
    )
    op.drop_constraint(None, 'user_regions', type_='foreignkey')
    op.drop_column('user_regions', 'updated_at')
    op.drop_column('user_regions', 'created_at')
    op.drop_column('user_regions', 'created_by')
    op.drop_constraint(None, 'user_permissions', type_='foreignkey')
    op.drop_column('user_permissions', 'created_by')
    op.drop_constraint(None, 'user_operation_logs', type_='foreignkey')
    op.drop_column('user_operation_logs', 'updated_at')
    op.drop_column('user_operation_logs', 'created_by')
    op.drop_constraint(None, 'user_menus', type_='foreignkey')
    op.drop_column('user_menus', 'created_by')
    op.drop_constraint(None, 'user_login_logs', type_='foreignkey')
    op.drop_column('user_login_logs', 'updated_at')
    op.drop_column('user_login_logs', 'created_by')
    op.drop_constraint(None, 'user_departments', type_='foreignkey')
    op.drop_column('user_departments', 'created_by')
    op.alter_column('institutions', 'created_by',
               existing_type=mysql.BIGINT(),
               nullable=False)
    op.drop_constraint(None, 'institution_credit_histories', type_='foreignkey')
    op.drop_column('institution_credit_histories', 'updated_at')
    op.drop_column('institution_credit_histories', 'created_by')
    op.alter_column('institution_credit_agreements', 'created_by',
               existing_type=mysql.BIGINT(),
               nullable=False)
    op.alter_column('institution_contacts', 'created_by',
               existing_type=mysql.BIGINT(),
               nullable=False)
    op.drop_column('institution_contacts', 'updated_at')
    op.alter_column('institution_branches', 'created_by',
               existing_type=mysql.BIGINT(),
               nullable=False)
    op.drop_column('institution_branches', 'updated_at')
    # customers：created_by → create_by 逆改名（原 FK 自动跟随）
    op.execute("ALTER TABLE customers RENAME COLUMN created_by TO create_by")
    op.drop_constraint(None, 'customer_tag_relations', type_='foreignkey')
    op.drop_column('customer_tag_relations', 'updated_at')
    op.drop_column('customer_tag_relations', 'created_by')
    op.drop_constraint(None, 'customer_shareholders', type_='foreignkey')
    op.drop_column('customer_shareholders', 'updated_at')
    op.drop_column('customer_shareholders', 'created_at')
    op.drop_column('customer_shareholders', 'created_by')
    op.drop_constraint(None, 'customer_personal_profiles', type_='foreignkey')
    op.drop_column('customer_personal_profiles', 'updated_at')
    op.drop_column('customer_personal_profiles', 'created_at')
    op.drop_column('customer_personal_profiles', 'created_by')
    op.drop_constraint(None, 'customer_industries', type_='foreignkey')
    op.drop_column('customer_industries', 'updated_at')
    op.drop_column('customer_industries', 'created_at')
    op.drop_column('customer_industries', 'created_by')
    op.alter_column('customer_groups', 'created_by',
               existing_type=mysql.BIGINT(),
               nullable=False)
    op.alter_column('customer_extra_tags', 'created_by',
               existing_type=mysql.BIGINT(),
               nullable=False)
    op.alter_column('customer_extends', 'created_by',
               existing_type=mysql.BIGINT(),
               nullable=False)
    op.drop_column('customer_extends', 'updated_at')
    op.drop_constraint(None, 'customer_directors', type_='foreignkey')
    op.drop_column('customer_directors', 'updated_at')
    op.drop_column('customer_directors', 'created_at')
    op.drop_column('customer_directors', 'created_by')
    op.alter_column('customer_credit_regions', 'created_by',
               existing_type=mysql.BIGINT(),
               nullable=False)
    op.drop_constraint(None, 'customer_core_limits', type_='foreignkey')
    op.drop_column('customer_core_limits', 'updated_at')
    op.drop_column('customer_core_limits', 'created_at')
    op.drop_column('customer_core_limits', 'created_by')
    op.drop_constraint(None, 'customer_core_histories', type_='foreignkey')
    op.drop_column('customer_core_histories', 'created_at')
    op.drop_column('customer_core_histories', 'created_by')
    op.drop_constraint(None, 'customer_company_profiles', type_='foreignkey')
    op.drop_column('customer_company_profiles', 'updated_at')
    op.drop_column('customer_company_profiles', 'created_at')
    op.drop_column('customer_company_profiles', 'created_by')
    op.drop_constraint(None, 'attachments', type_='foreignkey')
    op.drop_column('attachments', 'updated_at')
    op.drop_column('attachments', 'created_by')
    op.drop_constraint(None, 'approval_tasks', type_='foreignkey')
    op.drop_column('approval_tasks', 'updated_at')
    op.drop_column('approval_tasks', 'created_at')
    op.drop_column('approval_tasks', 'created_by')
    op.drop_constraint(None, 'approval_instances', type_='foreignkey')
    op.drop_column('approval_instances', 'updated_at')
    op.drop_column('approval_instances', 'created_at')
    op.drop_column('approval_instances', 'created_by')
    op.drop_constraint(None, 'approval_flow_nodes', type_='foreignkey')
    op.drop_column('approval_flow_nodes', 'updated_at')
    op.drop_column('approval_flow_nodes', 'created_at')
    op.drop_column('approval_flow_nodes', 'created_by')
    op.drop_constraint(None, 'approval_flow_defs', type_='foreignkey')
    op.drop_column('approval_flow_defs', 'updated_at')
    op.drop_column('approval_flow_defs', 'created_by')
    # ### end Alembic commands ###
