"""customer.controler_id nullable

Revision ID: b69d7e2b1c5e
Revises: 6d371af47fa4
Create Date: 2026-08-31 15:26:14.497918

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'b69d7e2b1c5e'
down_revision: Union[str, None] = '6d371af47fa4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('customers', 'controler_id',
               existing_type=mysql.BIGINT(),
               nullable=True,
               existing_comment='风控专员')
    op.alter_column('warrant_houses', 'house_locate',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255),
               comment='坐落（换证后同坐落可能出现多套证，不唯一）',
               existing_comment='坐落（唯一）',
               existing_nullable=False)
    op.alter_column('warrant_ownerships', 'ownership_num',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=128),
               comment='产权证编号（全局唯一）',
               existing_comment='产权证编号',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('warrant_ownerships', 'ownership_num',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=128),
               comment='产权证编号',
               existing_comment='产权证编号（全局唯一）',
               existing_nullable=False)
    op.alter_column('warrant_houses', 'house_locate',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255),
               comment='坐落（唯一）',
               existing_comment='坐落（换证后同坐落可能出现多套证，不唯一）',
               existing_nullable=False)
    op.alter_column('customers', 'controler_id',
               existing_type=mysql.BIGINT(),
               nullable=False,
               existing_comment='风控专员')
    # ### end Alembic commands ###
