"""drop_article_feedback_submitted_by_at

Revision ID: 0f093581a13d
Revises: 52fdfbcf8757
Create Date: 2026-09-11 16:41:11.445360

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '0f093581a13d'
down_revision: Union[str, None] = '52fdfbcf8757'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('article_feedbacks_ibfk_3'), 'article_feedbacks', type_='foreignkey')
    op.drop_column('article_feedbacks', 'submitted_by')
    op.drop_column('article_feedbacks', 'submitted_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article_feedbacks', sa.Column('submitted_at', sa.DATE(), nullable=True, comment='提交日期'))
    op.add_column('article_feedbacks', sa.Column('submitted_by', mysql.BIGINT(), autoincrement=False, nullable=True, comment='提交人'))
    op.create_foreign_key(op.f('article_feedbacks_ibfk_3'), 'article_feedbacks', 'users', ['submitted_by'], ['id'], ondelete='RESTRICT')
    # ### end Alembic commands ###
