"""warrant_construction_region

Revision ID: 449c7112a19e
Revises: 8254f71a7920
Create Date: 2026-08-31 18:10:19.059708

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '449c7112a19e'
down_revision: Union[str, None] = '8254f71a7920'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('warrant_constructions', sa.Column('region_id', sa.BigInteger(), nullable=True, comment='行政区域（方便按区域统计）'))
    op.alter_column('warrant_constructions', 'construct_locate',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255),
               comment='详细地址',
               existing_nullable=False)
    op.create_index(op.f('ix_warrant_constructions_region_id'), 'warrant_constructions', ['region_id'], unique=False)
    op.create_foreign_key(None, 'warrant_constructions', 'user_regions', ['region_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'warrant_constructions', type_='foreignkey')
    op.drop_index(op.f('ix_warrant_constructions_region_id'), table_name='warrant_constructions')
    op.alter_column('warrant_constructions', 'construct_locate',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255),
               comment=None,
               existing_comment='详细地址',
               existing_nullable=False)
    op.drop_column('warrant_constructions', 'region_id')
    # ### end Alembic commands ###
