"""group_add_status

Revision ID: 6552ff1b13e5
Revises: 6da424702f0b
Create Date: 2026-08-29 23:44:25.273436

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6552ff1b13e5'
down_revision: Union[str, None] = '6da424702f0b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # 存量集团（含历史上从未落库的 status）统一置 10 启用
    op.add_column('customer_groups', sa.Column(
        'status', sa.SmallInteger(), nullable=False,
        server_default='10', comment='10启用20停用'))
    op.alter_column('customer_groups', 'status', server_default=None)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customer_groups', 'status')
    # ### end Alembic commands ###
