"""add article and appraisal modules

Revision ID: 0212709b1d34
Revises: 20260903_b3f1a8e7c4d5
Create Date: 2026-09-03 19:48:29.262952

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '0212709b1d34'
down_revision: Union[str, None] = '20260903_b3f1a8e7c4d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('appraisal_expert_categories',
    sa.Column('name', sa.String(length=32), nullable=False, comment='类别名称'),
    sa.Column('sort', sa.Integer(), nullable=False),
    sa.Column('status', sa.SmallInteger(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('appraisals',
    sa.Column('num', sa.String(length=32), nullable=False, comment='评审会编号 年-次序'),
    sa.Column('year', sa.Integer(), nullable=False, comment='评审年份'),
    sa.Column('seq', sa.Integer(), nullable=False, comment='评审次序（年份内递增）'),
    sa.Column('review_model', sa.SmallInteger(), nullable=False, comment='评审类型'),
    sa.Column('review_date', sa.Date(), nullable=False, comment='评审日期'),
    sa.Column('compere_id', sa.BigInteger(), nullable=True, comment='主持人'),
    sa.Column('meeting_state', sa.SmallInteger(), nullable=False, comment='10待上会/20已上会'),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['compere_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('num'),
    sa.UniqueConstraint('year', 'seq', 'review_model', name='uq_appraisal_year_seq_model')
    )
    op.create_index('idx_appraisal_created_at', 'appraisals', ['created_at'], unique=False)
    op.create_index(op.f('ix_appraisals_meeting_state'), 'appraisals', ['meeting_state'], unique=False)
    op.create_table('article_products',
    sa.Column('name', sa.String(length=64), nullable=False, comment='产品名称'),
    sa.Column('difficulty_score', sa.Numeric(precision=6, scale=2), nullable=False, comment='难度系数'),
    sa.Column('sort', sa.Integer(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('appraisal_review_experts',
    sa.Column('name', sa.String(length=64), nullable=False, comment='姓名'),
    sa.Column('title', sa.String(length=64), nullable=True, comment='职务'),
    sa.Column('org_name', sa.String(length=128), nullable=True, comment='挂靠单位（文本快照）'),
    sa.Column('expert_type', sa.SmallInteger(), nullable=False, comment='10内部/20外部'),
    sa.Column('category_id', sa.BigInteger(), nullable=True, comment='专家类别'),
    sa.Column('contact_numb', sa.String(length=16), nullable=True, comment='联系电话'),
    sa.Column('email', sa.String(length=64), nullable=True, comment='邮箱'),
    sa.Column('sort', sa.Integer(), nullable=False),
    sa.Column('status', sa.SmallInteger(), nullable=False, comment='1启用/0停用(软删)'),
    sa.Column('remark', sa.String(length=255), nullable=True),
    sa.Column('deleted_at', sa.String(length=32), nullable=True, comment='软删时间'),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['appraisal_expert_categories.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('articles',
    sa.Column('article_num', sa.String(length=32), nullable=False, comment='项目编号'),
    sa.Column('article_state', sa.SmallInteger(), nullable=False, comment='项目状态机'),
    sa.Column('customer_id', sa.BigInteger(), nullable=False, comment='客户'),
    sa.Column('product_id', sa.BigInteger(), nullable=False, comment='产品类型'),
    sa.Column('renewal', sa.Numeric(precision=18, scale=2), nullable=False, comment='续贷金额'),
    sa.Column('augment', sa.Numeric(precision=18, scale=2), nullable=False, comment='新增金额'),
    sa.Column('credit_term', sa.SmallInteger(), nullable=False, comment='授信期限(月)'),
    sa.Column('repay_method', sa.SmallInteger(), nullable=True, comment='还款方式'),
    sa.Column('director_id', sa.BigInteger(), nullable=False, comment='项目经理'),
    sa.Column('assistant_id', sa.BigInteger(), nullable=True, comment='项目助理'),
    sa.Column('control_id', sa.BigInteger(), nullable=True, comment='风控专员'),
    sa.Column('review_date', sa.Date(), nullable=True, comment='上会日期(评审模块写入)'),
    sa.Column('summary_num', sa.String(length=32), nullable=True, comment='纪要编号(评审模块生成)'),
    sa.Column('summary', sa.Text(), nullable=True, comment='纪要'),
    sa.Column('opinion', sa.Text(), nullable=True, comment='项目意见'),
    sa.Column('rcd_opinion', sa.Text(), nullable=True, comment='风控部意见(签批时录入)'),
    sa.Column('convenor_opinion', sa.Text(), nullable=True, comment='招集人意见'),
    sa.Column('sign_detail', sa.Text(), nullable=True, comment='签批人意见'),
    sa.Column('sign_type', sa.SmallInteger(), nullable=True, comment='签批结论 1同意 2不同意'),
    sa.Column('sign_date', sa.Date(), nullable=True, comment='签批日期'),
    sa.Column('notify_sum', sa.Numeric(precision=18, scale=2), nullable=False, comment='通知金额(缓存)'),
    sa.Column('provide_sum', sa.Numeric(precision=18, scale=2), nullable=False, comment='放款金额(缓存)'),
    sa.Column('repayment_sum', sa.Numeric(precision=18, scale=2), nullable=False, comment='还款金额(缓存)'),
    sa.Column('balance', sa.Numeric(precision=18, scale=2), nullable=False, comment='在保余额(缓存)'),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['assistant_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['control_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['director_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['product_id'], ['article_products.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('article_num'),
    sa.UniqueConstraint('summary_num')
    )
    op.create_index('idx_article_created_at', 'articles', ['created_at'], unique=False)
    op.create_index(op.f('ix_articles_article_state'), 'articles', ['article_state'], unique=False)
    op.create_table('appraisal_articles',
    sa.Column('appraisal_id', sa.BigInteger(), nullable=False),
    sa.Column('article_id', sa.BigInteger(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['appraisal_id'], ['appraisals.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('appraisal_id', 'article_id', name='uq_appraisal_article')
    )
    op.create_table('appraisal_comments',
    sa.Column('article_id', sa.BigInteger(), nullable=False),
    sa.Column('expert_id', sa.BigInteger(), nullable=False),
    sa.Column('comment_type', sa.SmallInteger(), nullable=False, comment='0未发表/10同意/20复议/30不同意'),
    sa.Column('concrete', sa.Text(), nullable=True, comment='意见详情'),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['expert_id'], ['appraisal_review_experts.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('article_id', 'expert_id', name='uq_comment_article_expert')
    )
    op.create_table('appraisal_supplies',
    sa.Column('article_id', sa.BigInteger(), nullable=False),
    sa.Column('supply_detail', sa.Text(), nullable=False, comment='补调问题'),
    sa.Column('is_resolved', sa.Boolean(), nullable=False, comment='是否已解决'),
    sa.Column('resolve_reply', sa.Text(), nullable=True, comment='补调回复'),
    sa.Column('resolved_by', sa.BigInteger(), nullable=True, comment='解决登记人'),
    sa.Column('supplyor_id', sa.BigInteger(), nullable=False, comment='创建人'),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['resolved_by'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['supplyor_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('article_borrowers',
    sa.Column('article_id', sa.BigInteger(), nullable=False),
    sa.Column('customer_id', sa.BigInteger(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('article_id', 'customer_id', name='uq_borrower_article_customer')
    )
    op.create_table('article_changes',
    sa.Column('article_id', sa.BigInteger(), nullable=False),
    sa.Column('change_view', sa.SmallInteger(), nullable=False, comment='变更结论'),
    sa.Column('change_detail', sa.Text(), nullable=True, comment='变更详情'),
    sa.Column('change_date', sa.Date(), nullable=True, comment='变更日期'),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('article_feedbacks',
    sa.Column('article_id', sa.BigInteger(), nullable=False),
    sa.Column('propose', sa.SmallInteger(), nullable=True, comment='上会建议'),
    sa.Column('analysis', sa.Text(), nullable=True, comment='风险分析'),
    sa.Column('suggestion', sa.Text(), nullable=True, comment='风控意见'),
    sa.Column('submitted_by', sa.BigInteger(), nullable=True, comment='提交人'),
    sa.Column('submitted_at', sa.Date(), nullable=True, comment='提交日期'),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['submitted_by'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('article_id')
    )
    op.create_table('article_lending_orders',
    sa.Column('article_id', sa.BigInteger(), nullable=False),
    sa.Column('seq', sa.SmallInteger(), nullable=False, comment='发放次序 1-5'),
    sa.Column('order_amount', sa.Numeric(precision=18, scale=2), nullable=False, comment='拟放金额'),
    sa.Column('remark', sa.Text(), nullable=True),
    sa.Column('state', sa.SmallInteger(), nullable=False, comment='次序状态（跟随项目状态机）'),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('article_id', 'seq', name='uq_lending_order_article_seq')
    )
    op.create_table('article_mortgage_exts',
    sa.Column('article_id', sa.BigInteger(), nullable=False),
    sa.Column('product_type', sa.String(length=64), nullable=True, comment='业务品种'),
    sa.Column('provide_bank', sa.String(length=64), nullable=True, comment='放款银行'),
    sa.Column('credit_type', sa.String(length=64), nullable=True, comment='授信类型'),
    sa.Column('custom_unit', sa.String(length=128), nullable=True, comment='申请单位'),
    sa.Column('provide_term', sa.String(length=32), nullable=True, comment='放款期限'),
    sa.Column('entity_name', sa.String(length=128), nullable=True, comment='主体名称'),
    sa.Column('entity_owner', sa.String(length=64), nullable=True, comment='主体所有人'),
    sa.Column('owner_link', sa.String(length=64), nullable=True, comment='与借款人关系'),
    sa.Column('license_type', sa.String(length=64), nullable=True, comment='证照类型'),
    sa.Column('license_no', sa.String(length=64), nullable=True, comment='证照号'),
    sa.Column('register_date', sa.Date(), nullable=True, comment='登记日期'),
    sa.Column('register_addr', sa.String(length=255), nullable=True, comment='登记地址'),
    sa.Column('industry_c', sa.String(length=64), nullable=True, comment='行业'),
    sa.Column('mate_unit', sa.String(length=128), nullable=True, comment='配偶单位'),
    sa.Column('ownership_structure', mysql.JSON(), nullable=True, comment='股东结构（动态行，允许 JSON）'),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('article_id')
    )
    op.create_table('article_single_quotas',
    sa.Column('article_id', sa.BigInteger(), nullable=False),
    sa.Column('credit_model', sa.SmallInteger(), nullable=False, comment='授信类型'),
    sa.Column('credit_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('flow_rate', sa.Text(), nullable=True, comment='费率（文本）'),
    sa.Column('remark', sa.Text(), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('article_id', 'credit_model', name='uq_single_quota_article_model')
    )
    op.create_table('article_sures',
    sa.Column('article_id', sa.BigInteger(), nullable=False),
    sa.Column('sure_type', sa.SmallInteger(), nullable=False, comment='反担保类型'),
    sa.Column('remark', sa.Text(), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('article_id', 'sure_type', name='uq_sure_article_type')
    )
    op.create_table('article_sure_customers',
    sa.Column('sure_id', sa.BigInteger(), nullable=False),
    sa.Column('customer_id', sa.BigInteger(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['sure_id'], ['article_sures.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sure_id', 'customer_id', name='uq_sure_customer_sure_customer')
    )
    op.alter_column('warrant_stocks', 'registered_capital',
               existing_type=mysql.DECIMAL(precision=18, scale=2),
               comment='注册资本(万元)',
               existing_nullable=False)
    op.alter_column('warrant_stocks', 'paid_capital',
               existing_type=mysql.DECIMAL(precision=18, scale=2),
               comment='实收资本(万元)',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('warrant_stocks', 'paid_capital',
               existing_type=mysql.DECIMAL(precision=18, scale=2),
               comment=None,
               existing_comment='实收资本(万元)',
               existing_nullable=False)
    op.alter_column('warrant_stocks', 'registered_capital',
               existing_type=mysql.DECIMAL(precision=18, scale=2),
               comment=None,
               existing_comment='注册资本(万元)',
               existing_nullable=False)
    op.drop_table('article_sure_customers')
    op.drop_table('article_sures')
    op.drop_table('article_single_quotas')
    op.drop_table('article_mortgage_exts')
    op.drop_table('article_lending_orders')
    op.drop_table('article_feedbacks')
    op.drop_table('article_changes')
    op.drop_table('article_borrowers')
    op.drop_table('appraisal_supplies')
    op.drop_table('appraisal_comments')
    op.drop_table('appraisal_articles')
    op.drop_index(op.f('ix_articles_article_state'), table_name='articles')
    op.drop_index('idx_article_created_at', table_name='articles')
    op.drop_table('articles')
    op.drop_table('appraisal_review_experts')
    op.drop_table('article_products')
    op.drop_index(op.f('ix_appraisals_meeting_state'), table_name='appraisals')
    op.drop_index('idx_appraisal_created_at', table_name='appraisals')
    op.drop_table('appraisals')
    op.drop_table('appraisal_expert_categories')
    # ### end Alembic commands ###
