"""drop group status

Revision ID: 6da424702f0b
Revises: bbaf5aaf8416
Create Date: 2026-08-29 23:15:35.024960

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '6da424702f0b'
down_revision: Union[str, None] = 'bbaf5aaf8416'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customer_groups', 'status')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customer_groups', sa.Column('status', mysql.SMALLINT(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
