"""add_default_90_to_personal_profile_marital_status

Revision ID: 8ebb29be728a
Revises: 7d3e9f8a2b15
Create Date: 2026-09-02 08:01:40.200377

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '8ebb29be728a'
down_revision: Union[str, None] = '7d3e9f8a2b15'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('customer_core_limits', 'status',
               existing_type=mysql.SMALLINT(),
               comment='10生效20失效30用完',
               existing_comment='10生效20失效30已用完',
               existing_nullable=False)
    op.alter_column('warrant_houses', 'house_name',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=128),
               comment='楼盘名',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('warrant_houses', 'house_name',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=128),
               comment=None,
               existing_comment='楼盘名',
               existing_nullable=True)
    op.alter_column('customer_core_limits', 'status',
               existing_type=mysql.SMALLINT(),
               comment='10生效20失效30已用完',
               existing_comment='10生效20失效30用完',
               existing_nullable=False)
    # ### end Alembic commands ###
