"""M2: institution/customer/warrant/approval/attachment tables

Revision ID: 1aa1b11ec9a9
Revises: 0001
Create Date: 2026-08-26 15:23:03.695069

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '1aa1b11ec9a9'
down_revision: Union[str, None] = '0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('approval_flow_defs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False, comment='流程编码'),
    sa.Column('name', sa.String(length=64), nullable=False, comment='流程名称'),
    sa.Column('version', sa.SmallInteger(), nullable=False, comment='版本号'),
    sa.Column('status', sa.SmallInteger(), nullable=False, comment='10启用20停用'),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_index('idx_flow_def_code', 'approval_flow_defs', ['code'], unique=False)
    op.create_table('customer_industries',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=16), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('ind_typ', sa.SmallInteger(), nullable=False, comment='10一产20二产30三产'),
    sa.Column('parent_id', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_index(op.f('ix_customer_industries_parent_id'), 'customer_industries', ['parent_id'], unique=False)
    op.create_table('customer_regions',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=12), nullable=False, comment='行政区划代码'),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('level', sa.SmallInteger(), nullable=False, comment='10省20市30区县40乡镇街道'),
    sa.Column('parent_id', sa.BigInteger(), nullable=False),
    sa.Column('ordery', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.SmallInteger(), nullable=False, comment='10启用20停用'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_index(op.f('ix_customer_regions_parent_id'), 'customer_regions', ['parent_id'], unique=False)
    op.create_table('warrant_house_apps',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('parent_id', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.SmallInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_warrant_house_apps_parent_id'), 'warrant_house_apps', ['parent_id'], unique=False)
    op.create_table('approval_flow_nodes',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('flow_def_id', sa.BigInteger(), nullable=False),
    sa.Column('step', sa.SmallInteger(), nullable=False, comment='节点顺序，从 1 开始'),
    sa.Column('name', sa.String(length=64), nullable=False, comment='节点名称'),
    sa.Column('approver_role_code', sa.String(length=64), nullable=False, comment='审批岗位角色 code'),
    sa.Column('approver_scope', sa.SmallInteger(), nullable=False, comment='10提交人本部门20提交人部门负责人'),
    sa.Column('or_sign', sa.Boolean(), nullable=False, comment='或签：任一人同意即过'),
    sa.Column('skip_condition', sa.String(length=255), nullable=True, comment='预留跳过条件'),
    sa.ForeignKeyConstraint(['flow_def_id'], ['approval_flow_defs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_flow_node_def_step', 'approval_flow_nodes', ['flow_def_id', 'step'], unique=False)
    op.create_index(op.f('ix_approval_flow_nodes_flow_def_id'), 'approval_flow_nodes', ['flow_def_id'], unique=False)
    op.create_table('approval_instances',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('flow_code', sa.String(length=64), nullable=False, comment='流程编码'),
    sa.Column('biz_type', sa.String(length=32), nullable=False, comment='业务对象类型'),
    sa.Column('biz_id', sa.BigInteger(), nullable=True, comment='业务对象 id'),
    sa.Column('payload', mysql.JSON(), nullable=False, comment='三模式载荷'),
    sa.Column('summary', sa.String(length=255), nullable=False, comment='申请摘要（列表展示）'),
    sa.Column('status', sa.SmallInteger(), nullable=False, comment='10审批中20通过30驳回40撤回'),
    sa.Column('current_step', sa.SmallInteger(), nullable=False, comment='当前节点 step'),
    sa.Column('submitted_by', sa.BigInteger(), nullable=False),
    sa.Column('submitted_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['submitted_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_inst_biz', 'approval_instances', ['biz_type', 'biz_id', 'status'], unique=False)
    op.create_index(op.f('ix_approval_instances_biz_id'), 'approval_instances', ['biz_id'], unique=False)
    op.create_index(op.f('ix_approval_instances_biz_type'), 'approval_instances', ['biz_type'], unique=False)
    op.create_index(op.f('ix_approval_instances_flow_code'), 'approval_instances', ['flow_code'], unique=False)
    op.create_index(op.f('ix_approval_instances_status'), 'approval_instances', ['status'], unique=False)
    op.create_index(op.f('ix_approval_instances_submitted_by'), 'approval_instances', ['submitted_by'], unique=False)
    op.create_table('attachments',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('resource_type', sa.String(length=32), nullable=False, comment='资源类型：customer/agree/article/lend...'),
    sa.Column('resource_id', sa.BigInteger(), nullable=False, comment='资源 id'),
    sa.Column('file_name', sa.String(length=255), nullable=False, comment='原始文件名'),
    sa.Column('file_path', sa.String(length=512), nullable=False),
    sa.Column('file_size', sa.BigInteger(), nullable=False, comment='字节'),
    sa.Column('mime_type', sa.String(length=128), nullable=True),
    sa.Column('remark', sa.String(length=255), nullable=True),
    sa.Column('uploaded_by', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_attachment_resource', 'attachments', ['resource_type', 'resource_id'], unique=False)
    op.create_index(op.f('ix_attachments_uploaded_by'), 'attachments', ['uploaded_by'], unique=False)
    op.create_table('customer_credit_regions',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('parent_id', sa.BigInteger(), nullable=False),
    sa.Column('credit_amount', sa.Numeric(precision=18, scale=2), nullable=False, comment='区域授信总额度'),
    sa.Column('used_amount', sa.Numeric(precision=18, scale=2), nullable=False, comment='已用额度(冗余,异步刷新)'),
    sa.Column('platform_name', sa.String(length=128), nullable=True, comment='平台名称'),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('status', sa.SmallInteger(), nullable=False, comment='10启用20停用'),
    sa.Column('created_by', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_index(op.f('ix_customer_credit_regions_parent_id'), 'customer_credit_regions', ['parent_id'], unique=False)
    op.create_table('customer_extra_tags',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('type', sa.SmallInteger(), nullable=False, comment='10行业20业务标签'),
    sa.Column('status', sa.SmallInteger(), nullable=False),
    sa.Column('created_by', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('customer_groups',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('parent_id', sa.BigInteger(), nullable=False),
    sa.Column('parent_customer_id', sa.BigInteger(), nullable=True, comment='母公司客户'),
    sa.Column('credit_amount', sa.Numeric(precision=18, scale=2), nullable=False, comment='集团总授信额度'),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('status', sa.SmallInteger(), nullable=False),
    sa.Column('created_by', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['parent_customer_id'], ['customers.id'], name='fk_group_parent_customer', use_alter=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_customer_groups_parent_customer_id'), 'customer_groups', ['parent_customer_id'], unique=False)
    op.create_index(op.f('ix_customer_groups_parent_id'), 'customer_groups', ['parent_id'], unique=False)
    op.create_table('institutions',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False, comment='机构全称'),
    sa.Column('short_name', sa.String(length=32), nullable=False, comment='简称'),
    sa.Column('institution_type', sa.SmallInteger(), nullable=False, comment='10银行20担保30律所40评估50会计师90其他'),
    sa.Column('institution_subtype', sa.SmallInteger(), nullable=True, comment='银行子类型'),
    sa.Column('credit_code', sa.String(length=32), nullable=True, comment='统一社会信用代码'),
    sa.Column('legal_representative', sa.String(length=64), nullable=True, comment='法人代表'),
    sa.Column('registered_addr', sa.String(length=255), nullable=True, comment='注册地址'),
    sa.Column('contact_addr', sa.String(length=255), nullable=True, comment='联系地址'),
    sa.Column('contact_num', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=128), nullable=True),
    sa.Column('up_scale', sa.Numeric(precision=6, scale=2), nullable=True, comment='最高额上浮比例%（银行类）'),
    sa.Column('used_flow', sa.Numeric(precision=18, scale=2), nullable=False, comment='已用流贷余额'),
    sa.Column('used_accept', sa.Numeric(precision=18, scale=2), nullable=False, comment='已用承兑余额'),
    sa.Column('used_back', sa.Numeric(precision=18, scale=2), nullable=False, comment='已用保函余额'),
    sa.Column('used_entrusted', sa.Numeric(precision=18, scale=2), nullable=False, comment='已用委贷余额'),
    sa.Column('used_amount', sa.Numeric(precision=18, scale=2), nullable=False, comment='在保总额'),
    sa.Column('last_synced_at', sa.DateTime(), nullable=True, comment='冗余字段最后刷新时间'),
    sa.Column('status', sa.SmallInteger(), nullable=False, comment='10正常20停用90注销'),
    sa.Column('created_by', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('short_name')
    )
    op.create_index(op.f('ix_institutions_institution_type'), 'institutions', ['institution_type'], unique=False)
    op.create_index(op.f('ix_institutions_status'), 'institutions', ['status'], unique=False)
    op.create_table('warrant_evaluate_companies',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('created_by', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('warrants',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('warrant_num', sa.String(length=128), nullable=False, comment='权证编号'),
    sa.Column('warrant_type', sa.SmallInteger(), nullable=False, comment='1房产5土地6在建11应收21股权31票据41车辆51动产55其他99他权'),
    sa.Column('evaluate_method', sa.SmallInteger(), nullable=True, comment='评估方式'),
    sa.Column('evaluate_value', sa.Numeric(precision=18, scale=2), nullable=True, comment='评估价值'),
    sa.Column('evaluate_date', sa.Date(), nullable=True),
    sa.Column('evaluate_explain', sa.String(length=255), nullable=True),
    sa.Column('evaluate_company', sa.String(length=128), nullable=True),
    sa.Column('meeting_date', sa.Date(), nullable=True, comment='最近上会日'),
    sa.Column('warrant_state', sa.SmallInteger(), nullable=False, comment='10未入库20已入库30已加保60无需入库110续抵出库210已借出310解保出库410已移交990已注销'),
    sa.Column('storage_explain', sa.String(length=255), nullable=True),
    sa.Column('inquiry_date', sa.Date(), nullable=True, comment='查询日期'),
    sa.Column('inquiry_detail', sa.String(length=255), nullable=True, comment='查封详情'),
    sa.Column('auction_state', sa.SmallInteger(), nullable=False, comment='拍卖状态'),
    sa.Column('auction_date', sa.Date(), nullable=True),
    sa.Column('listing_price', sa.Numeric(precision=18, scale=2), nullable=True, comment='挂网价'),
    sa.Column('auction_remark', sa.String(length=255), nullable=True),
    sa.Column('transaction_date', sa.Date(), nullable=True, comment='成交日'),
    sa.Column('auction_amount', sa.Numeric(precision=18, scale=2), nullable=True, comment='成交价'),
    sa.Column('created_by', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('warrant_num')
    )
    op.create_index(op.f('ix_warrants_auction_state'), 'warrants', ['auction_state'], unique=False)
    op.create_index(op.f('ix_warrants_created_by'), 'warrants', ['created_by'], unique=False)
    op.create_index(op.f('ix_warrants_warrant_state'), 'warrants', ['warrant_state'], unique=False)
    op.create_index(op.f('ix_warrants_warrant_type'), 'warrants', ['warrant_type'], unique=False)
    op.create_table('approval_tasks',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('instance_id', sa.BigInteger(), nullable=False),
    sa.Column('step', sa.SmallInteger(), nullable=False, comment='对应节点 step'),
    sa.Column('node_name', sa.String(length=64), nullable=False, comment='节点名称冗余'),
    sa.Column('approver_id', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.SmallInteger(), nullable=False, comment='10待审20同意30驳回40跳过50取消'),
    sa.Column('opinion', sa.String(length=500), nullable=True, comment='审批意见'),
    sa.Column('acted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['approver_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['instance_id'], ['approval_instances.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_task_instance_step', 'approval_tasks', ['instance_id', 'step'], unique=False)
    op.create_index(op.f('ix_approval_tasks_approver_id'), 'approval_tasks', ['approver_id'], unique=False)
    op.create_index(op.f('ix_approval_tasks_instance_id'), 'approval_tasks', ['instance_id'], unique=False)
    op.create_index(op.f('ix_approval_tasks_status'), 'approval_tasks', ['status'], unique=False)
    op.create_table('customers',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('short_name', sa.String(length=32), nullable=False),
    sa.Column('genre', sa.SmallInteger(), nullable=False, comment='1企业2个人'),
    sa.Column('custom_typ', sa.SmallInteger(), nullable=False, comment='10新增20存量30存量新增'),
    sa.Column('custom_state', sa.SmallInteger(), nullable=False, comment='10正常20反担保30小贷90注销'),
    sa.Column('contact_addr', sa.String(length=255), nullable=True),
    sa.Column('linkman', sa.String(length=64), nullable=True),
    sa.Column('contact_num', sa.String(length=64), nullable=True),
    sa.Column('region_id', sa.BigInteger(), nullable=True, comment='行政区域'),
    sa.Column('credit_region_id', sa.BigInteger(), nullable=True, comment='授信区域'),
    sa.Column('industry_id', sa.BigInteger(), nullable=True, comment='国民经济行业'),
    sa.Column('group_id', sa.BigInteger(), nullable=True, comment='所属集团'),
    sa.Column('is_core', sa.Boolean(), nullable=False, comment='票据核心企业'),
    sa.Column('is_acceptor', sa.Boolean(), nullable=False, comment='票据承兑人'),
    sa.Column('managementor_id', sa.BigInteger(), nullable=False, comment='管护经理'),
    sa.Column('controler_id', sa.BigInteger(), nullable=False, comment='风控专员'),
    sa.Column('create_by', sa.BigInteger(), nullable=False, comment='创建人'),
    sa.Column('core_rate', sa.Numeric(precision=6, scale=2), nullable=True, comment='核心企业费率%'),
    sa.Column('core_remark', sa.String(length=255), nullable=True, comment='核心企业备注'),
    sa.Column('credit_amount', sa.Numeric(precision=18, scale=2), nullable=False, comment='授信总额'),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False, comment='在保总额'),
    sa.Column('custom_flow', sa.Numeric(precision=18, scale=2), nullable=False, comment='流贷余额'),
    sa.Column('custom_accept', sa.Numeric(precision=18, scale=2), nullable=False, comment='承兑余额'),
    sa.Column('custom_back', sa.Numeric(precision=18, scale=2), nullable=False, comment='保函余额'),
    sa.Column('entrusted_loan', sa.Numeric(precision=18, scale=2), nullable=False, comment='委贷余额'),
    sa.Column('g_value', sa.Numeric(precision=18, scale=2), nullable=False, comment='反担保价值'),
    sa.Column('g_radio', sa.Numeric(precision=8, scale=2), nullable=False, comment='授信覆盖率%'),
    sa.Column('v_radio', sa.Numeric(precision=8, scale=2), nullable=False, comment='在保覆盖率%'),
    sa.Column('classification', sa.SmallInteger(), nullable=False, comment='五级分类'),
    sa.Column('sales_revenue', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('total_assets', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('people_engaged', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('data_date', sa.Date(), nullable=True, comment='快照基准日'),
    sa.Column('last_provide_date', sa.Date(), nullable=True, comment='最近放款'),
    sa.Column('last_review_date', sa.Date(), nullable=True, comment='最近保后'),
    sa.Column('day_space', sa.BigInteger(), nullable=False, comment='距上次更新间隔日'),
    sa.Column('last_synced_at', sa.DateTime(), nullable=True, comment='冗余字段最后刷新时间'),
    sa.Column('tags', mysql.JSON(), nullable=True, comment='标签 id 数组'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['controler_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['create_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['credit_region_id'], ['customer_credit_regions.id'], ),
    sa.ForeignKeyConstraint(['group_id'], ['customer_groups.id'], ),
    sa.ForeignKeyConstraint(['industry_id'], ['customer_industries.id'], ),
    sa.ForeignKeyConstraint(['managementor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['region_id'], ['customer_regions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('short_name')
    )
    op.create_index(op.f('ix_customers_classification'), 'customers', ['classification'], unique=False)
    op.create_index(op.f('ix_customers_credit_region_id'), 'customers', ['credit_region_id'], unique=False)
    op.create_index(op.f('ix_customers_custom_state'), 'customers', ['custom_state'], unique=False)
    op.create_index(op.f('ix_customers_genre'), 'customers', ['genre'], unique=False)
    op.create_index(op.f('ix_customers_group_id'), 'customers', ['group_id'], unique=False)
    op.create_index(op.f('ix_customers_is_acceptor'), 'customers', ['is_acceptor'], unique=False)
    op.create_index(op.f('ix_customers_is_core'), 'customers', ['is_core'], unique=False)
    op.create_index(op.f('ix_customers_managementor_id'), 'customers', ['managementor_id'], unique=False)
    op.create_index(op.f('ix_customers_name'), 'customers', ['name'], unique=False)
    op.create_index(op.f('ix_customers_region_id'), 'customers', ['region_id'], unique=False)
    # 循环依赖外键（customers.group_id ↔ customer_groups.parent_customer_id）：
    # use_alter 的约束不随 CREATE TABLE 下发，此处显式后置添加
    op.create_foreign_key(
        'fk_group_parent_customer', 'customer_groups', 'customers',
        ['parent_customer_id'], ['id'],
    )
    op.create_table('institution_branches',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('institution_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('short_name', sa.String(length=32), nullable=False),
    sa.Column('branch_addr', sa.String(length=255), nullable=True),
    sa.Column('contact_num', sa.String(length=64), nullable=True),
    sa.Column('status', sa.SmallInteger(), nullable=False, comment='10正常20停用90注销'),
    sa.Column('created_by', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('institution_id', 'name', name='uq_branch_inst_name')
    )
    op.create_index(op.f('ix_institution_branches_institution_id'), 'institution_branches', ['institution_id'], unique=False)
    op.create_index(op.f('ix_institution_branches_status'), 'institution_branches', ['status'], unique=False)
    op.create_table('institution_contacts',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('institution_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('job', sa.String(length=64), nullable=True, comment='职务'),
    sa.Column('phone', sa.String(length=16), nullable=False),
    sa.Column('email', sa.String(length=128), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=False, comment='首选联系人'),
    sa.Column('remark', sa.String(length=255), nullable=True),
    sa.Column('created_by', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('institution_id', 'name', name='uq_contact_inst_name')
    )
    op.create_index(op.f('ix_institution_contacts_institution_id'), 'institution_contacts', ['institution_id'], unique=False)
    op.create_table('institution_credit_agreements',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('institution_id', sa.BigInteger(), nullable=False),
    sa.Column('agreement_type', sa.SmallInteger(), nullable=False, comment='10综合授信20保函授信30服务协议40委贷协议'),
    sa.Column('flow_credit', sa.Numeric(precision=18, scale=2), nullable=False, comment='综合额度'),
    sa.Column('flow_limit', sa.Numeric(precision=18, scale=2), nullable=False, comment='单笔限额-综合'),
    sa.Column('back_credit', sa.Numeric(precision=18, scale=2), nullable=False, comment='保函额度'),
    sa.Column('back_limit', sa.Numeric(precision=18, scale=2), nullable=False, comment='单笔限额-保函'),
    sa.Column('entrusted_credit', sa.Numeric(precision=18, scale=2), nullable=True, comment='委贷额度'),
    sa.Column('valid_begin_date', sa.Date(), nullable=False),
    sa.Column('valid_end_date', sa.Date(), nullable=False),
    sa.Column('status', sa.SmallInteger(), nullable=False, comment='10生效20失效30已用完90已终止'),
    sa.Column('remark', sa.String(length=255), nullable=True),
    sa.Column('created_by', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_agreement_inst_status_type', 'institution_credit_agreements', ['institution_id', 'status', 'agreement_type'], unique=False)
    op.create_index(op.f('ix_institution_credit_agreements_agreement_type'), 'institution_credit_agreements', ['agreement_type'], unique=False)
    op.create_index(op.f('ix_institution_credit_agreements_institution_id'), 'institution_credit_agreements', ['institution_id'], unique=False)
    op.create_index(op.f('ix_institution_credit_agreements_status'), 'institution_credit_agreements', ['status'], unique=False)
    op.create_table('warrant_chattels',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('warrant_id', sa.BigInteger(), nullable=False),
    sa.Column('chattel_type', sa.SmallInteger(), nullable=False, comment='10存货20机器设备30医疗设备99动产'),
    sa.Column('chattel_detail', sa.String(length=255), nullable=False),
    sa.Column('created_by', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['warrant_id'], ['warrants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('warrant_id')
    )
    op.create_table('warrant_constructions',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('warrant_id', sa.BigInteger(), nullable=False),
    sa.Column('construct_locate', sa.String(length=255), nullable=False),
    sa.Column('construct_app', sa.String(length=128), nullable=False, comment='工程用途'),
    sa.Column('construct_area', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('created_by', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['warrant_id'], ['warrants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('warrant_id')
    )
    op.create_table('warrant_drafts',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('warrant_id', sa.BigInteger(), nullable=False),
    sa.Column('draft_detail', sa.String(length=255), nullable=False),
    sa.Column('denomination', sa.Numeric(precision=18, scale=2), nullable=False, comment='票面总额'),
    sa.Column('draft_type', sa.SmallInteger(), nullable=False, comment='10商业承兑20银行承兑30支票'),
    sa.Column('created_by', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['warrant_id'], ['warrants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('warrant_id')
    )
    op.create_table('warrant_evaluates',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('warrant_id', sa.BigInteger(), nullable=False),
    sa.Column('evaluate_method', sa.SmallInteger(), nullable=False),
    sa.Column('evaluate_value', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('evaluate_date', sa.Date(), nullable=False),
    sa.Column('evaluate_explain', sa.String(length=255), nullable=True),
    sa.Column('evaluate_company', sa.String(length=128), nullable=True),
    sa.Column('created_by', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['warrant_id'], ['warrants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_warrant_evaluates_warrant_id'), 'warrant_evaluates', ['warrant_id'], unique=False)
    op.create_table('warrant_grounds',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('warrant_id', sa.BigInteger(), nullable=False),
    sa.Column('ground_locate', sa.String(length=255), nullable=False),
    sa.Column('ground_app', sa.String(length=128), nullable=False, comment='土地用途'),
    sa.Column('ground_area', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('created_by', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['warrant_id'], ['warrants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('warrant_id')
    )
    op.create_table('warrant_houses',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('warrant_id', sa.BigInteger(), nullable=False),
    sa.Column('house_locate', sa.String(length=255), nullable=False, comment='坐落（唯一）'),
    sa.Column('house_app', sa.BigInteger(), nullable=False, comment='房产用途（字典）'),
    sa.Column('house_area', sa.Numeric(precision=12, scale=2), nullable=False, comment='面积'),
    sa.Column('house_name', sa.String(length=128), nullable=True),
    sa.Column('house_build_year', sa.SmallInteger(), nullable=True),
    sa.Column('house_usage', sa.SmallInteger(), nullable=False, comment='10自用20出租30空置'),
    sa.Column('created_by', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['warrant_id'], ['warrants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_warrant_houses_warrant_id'), 'warrant_houses', ['warrant_id'], unique=False)
    op.create_table('warrant_others',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('warrant_id', sa.BigInteger(), nullable=False),
    sa.Column('other_type', sa.SmallInteger(), nullable=False, comment='10购房合同20车辆合格证30专利40商标501软件著作权70账户99其他'),
    sa.Column('cost', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('other_detail', sa.String(length=255), nullable=False),
    sa.Column('created_by', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['warrant_id'], ['warrants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('warrant_id')
    )
    op.create_table('warrant_receivables',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('warrant_id', sa.BigInteger(), nullable=False),
    sa.Column('receivable_detail', sa.String(length=255), nullable=False),
    sa.Column('created_by', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['warrant_id'], ['warrants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('warrant_id')
    )
    op.create_table('warrant_stocks',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('warrant_id', sa.BigInteger(), nullable=False),
    sa.Column('stock_type', sa.SmallInteger(), nullable=False, comment='10有限公司股权20股份公司股份30举办者权益'),
    sa.Column('target', sa.String(length=128), nullable=False, comment='标的公司'),
    sa.Column('ratio', sa.Numeric(precision=5, scale=2), nullable=False, comment='持股%'),
    sa.Column('registered_capital', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('paid_capital', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('remark', sa.String(length=255), nullable=True),
    sa.Column('created_by', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['warrant_id'], ['warrants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('warrant_id')
    )
    op.create_table('warrant_storages',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('warrant_id', sa.BigInteger(), nullable=False),
    sa.Column('storage_type', sa.SmallInteger(), nullable=False, comment='10入库20续抵出库30已加保60无需入库110借出120归还310解保出库410移交'),
    sa.Column('storage_explain', sa.String(length=255), nullable=True),
    sa.Column('transfer_id', sa.BigInteger(), nullable=True, comment='移交/接收者'),
    sa.Column('conservator_id', sa.BigInteger(), nullable=False, comment='权证管理岗'),
    sa.Column('storage_date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['conservator_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['transfer_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['warrant_id'], ['warrants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_warrant_storages_warrant_id'), 'warrant_storages', ['warrant_id'], unique=False)
    op.create_table('warrant_vehicles',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('warrant_id', sa.BigInteger(), nullable=False),
    sa.Column('frame_num', sa.String(length=64), nullable=False, comment='车架号'),
    sa.Column('plate_num', sa.String(length=32), nullable=False, comment='车牌号'),
    sa.Column('vehicle_brand', sa.String(length=64), nullable=False),
    sa.Column('remark', sa.String(length=255), nullable=True),
    sa.Column('created_by', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['warrant_id'], ['warrants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('frame_num'),
    sa.UniqueConstraint('plate_num'),
    sa.UniqueConstraint('warrant_id')
    )
    op.create_table('customer_company_profiles',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('customer_id', sa.BigInteger(), nullable=False),
    sa.Column('credit_code', sa.String(length=32), nullable=False, comment='统一社会信用代码'),
    sa.Column('decisionor', sa.SmallInteger(), nullable=True, comment='决策机构'),
    sa.Column('custom_nature', sa.SmallInteger(), nullable=True, comment='企业性质'),
    sa.Column('industry_c', sa.BigInteger(), nullable=True, comment='工信部划分行业'),
    sa.Column('typing', sa.SmallInteger(), nullable=False, comment='企业划型'),
    sa.Column('capital', sa.Numeric(precision=18, scale=2), nullable=True, comment='注册资本'),
    sa.Column('paid_capital', sa.Numeric(precision=18, scale=2), nullable=True, comment='实收资本'),
    sa.Column('registered_addr', sa.String(length=255), nullable=True),
    sa.Column('representative', sa.String(length=64), nullable=True, comment='法人代表'),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('credit_code')
    )
    op.create_index(op.f('ix_customer_company_profiles_customer_id'), 'customer_company_profiles', ['customer_id'], unique=True)
    op.create_table('customer_core_histories',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('customer_id', sa.BigInteger(), nullable=False),
    sa.Column('change_content', mysql.JSON(), nullable=False),
    sa.Column('changed_by', sa.BigInteger(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['changed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customer_core_histories_customer_id'), 'customer_core_histories', ['customer_id'], unique=False)
    op.create_table('customer_core_limits',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('customer_id', sa.BigInteger(), nullable=False),
    sa.Column('credit_amount', sa.Numeric(precision=18, scale=2), nullable=False, comment='授信总额'),
    sa.Column('valid_begin_date', sa.Date(), nullable=False),
    sa.Column('valid_end_date', sa.Date(), nullable=False),
    sa.Column('used_amount', sa.Numeric(precision=18, scale=2), nullable=False, comment='已占用额'),
    sa.Column('remaining_amount', sa.Numeric(precision=18, scale=2), nullable=False, comment='剩余额'),
    sa.Column('status', sa.SmallInteger(), nullable=False, comment='10生效20失效30已用完'),
    sa.Column('remark', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('customer_id', 'valid_begin_date', name='uq_core_limit_date')
    )
    op.create_index(op.f('ix_customer_core_limits_customer_id'), 'customer_core_limits', ['customer_id'], unique=False)
    op.create_index(op.f('ix_customer_core_limits_status'), 'customer_core_limits', ['status'], unique=False)
    op.create_table('customer_extends',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('customer_id', sa.BigInteger(), nullable=False),
    sa.Column('sales_revenue', sa.Numeric(precision=18, scale=2), nullable=False, comment='销售收入'),
    sa.Column('total_assets', sa.Numeric(precision=18, scale=2), nullable=False, comment='总资产'),
    sa.Column('people_engaged', sa.Numeric(precision=12, scale=2), nullable=False, comment='从业人数'),
    sa.Column('data_date', sa.Date(), nullable=False, comment='快照基准日'),
    sa.Column('typing', sa.SmallInteger(), nullable=False, comment='划型结果'),
    sa.Column('created_by', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('customer_id', 'data_date', name='uq_extend_date')
    )
    op.create_index(op.f('ix_customer_extends_customer_id'), 'customer_extends', ['customer_id'], unique=False)
    op.create_table('customer_personal_profiles',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('customer_id', sa.BigInteger(), nullable=False),
    sa.Column('license_num', sa.String(length=18), nullable=False, comment='身份证号'),
    sa.Column('license_addr', sa.String(length=255), nullable=True),
    sa.Column('marital_status', sa.SmallInteger(), nullable=True, comment='婚姻状态'),
    sa.Column('household_nature', sa.SmallInteger(), nullable=True, comment='户籍性质'),
    sa.Column('spouse_id', sa.BigInteger(), nullable=True, comment='配偶（双向指向另一条个人客户）'),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['spouse_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('license_num')
    )
    op.create_index(op.f('ix_customer_personal_profiles_customer_id'), 'customer_personal_profiles', ['customer_id'], unique=True)
    op.create_table('institution_credit_histories',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('institution_id', sa.BigInteger(), nullable=False),
    sa.Column('agreement_id', sa.BigInteger(), nullable=True, comment='关联协议'),
    sa.Column('change_type', sa.SmallInteger(), nullable=False, comment='10新增协议20额度调整30协议到期40余额刷新'),
    sa.Column('change_content', mysql.JSON(), nullable=False, comment='{field,before,after,...}'),
    sa.Column('changed_by', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['agreement_id'], ['institution_credit_agreements.id'], ),
    sa.ForeignKeyConstraint(['changed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_institution_credit_histories_institution_id'), 'institution_credit_histories', ['institution_id'], unique=False)
    op.create_table('warrant_draft_extends',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('draft_id', sa.BigInteger(), nullable=False),
    sa.Column('draft_type', sa.SmallInteger(), nullable=False, comment='10电银承20银承11电商承12商承21支票'),
    sa.Column('draft_num', sa.String(length=128), nullable=False, comment='票据编号'),
    sa.Column('acceptor_id', sa.BigInteger(), nullable=False, comment='承兑人'),
    sa.Column('core_id', sa.BigInteger(), nullable=False, comment='核心企业'),
    sa.Column('draft_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('issue_date', sa.Date(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('draft_state', sa.SmallInteger(), nullable=False, comment='10未入库20已入库30已加保120已归还210置换出库310解保出库410托收出库990已注销'),
    sa.Column('created_by', sa.BigInteger(), nullable=False),
    sa.Column('updated_by', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['acceptor_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['core_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['draft_id'], ['warrant_drafts.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_draft_extend_num', 'warrant_draft_extends', ['draft_num'], unique=False)
    op.create_index(op.f('ix_warrant_draft_extends_acceptor_id'), 'warrant_draft_extends', ['acceptor_id'], unique=False)
    op.create_index(op.f('ix_warrant_draft_extends_core_id'), 'warrant_draft_extends', ['core_id'], unique=False)
    op.create_index(op.f('ix_warrant_draft_extends_draft_id'), 'warrant_draft_extends', ['draft_id'], unique=False)
    op.create_index(op.f('ix_warrant_draft_extends_draft_state'), 'warrant_draft_extends', ['draft_state'], unique=False)
    op.create_table('warrant_evaluate_rechecks',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('evaluate_id', sa.BigInteger(), nullable=False),
    sa.Column('check_value', sa.Numeric(precision=18, scale=2), nullable=False, comment='核查价值'),
    sa.Column('recheck_value', sa.Numeric(precision=18, scale=2), nullable=False, comment='复核价值'),
    sa.Column('recheck_channel', sa.String(length=128), nullable=False, comment='复核渠道'),
    sa.Column('remark', sa.String(length=255), nullable=True),
    sa.Column('created_by', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['evaluate_id'], ['warrant_evaluates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_warrant_evaluate_rechecks_evaluate_id'), 'warrant_evaluate_rechecks', ['evaluate_id'], unique=False)
    op.create_table('warrant_ownerships',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('warrant_id', sa.BigInteger(), nullable=False),
    sa.Column('ownership_num', sa.String(length=128), nullable=False, comment='产权证编号'),
    sa.Column('owner_id', sa.BigInteger(), nullable=False),
    sa.Column('share_ratio', sa.Numeric(precision=5, scale=2), nullable=True, comment='共有份额%，null=独有'),
    sa.Column('created_by', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['warrant_id'], ['warrants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('warrant_id', 'owner_id', name='uq_ownership_warrant_owner')
    )
    op.create_index(op.f('ix_warrant_ownerships_owner_id'), 'warrant_ownerships', ['owner_id'], unique=False)
    op.create_index(op.f('ix_warrant_ownerships_warrant_id'), 'warrant_ownerships', ['warrant_id'], unique=False)
    op.create_table('warrant_patents',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('other_id', sa.BigInteger(), nullable=False),
    sa.Column('patent_name', sa.String(length=128), nullable=False),
    sa.Column('reg_num', sa.String(length=64), nullable=False),
    sa.Column('patent_ty', sa.SmallInteger(), nullable=False, comment='商标类型'),
    sa.Column('created_by', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['other_id'], ['warrant_others.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('other_id'),
    sa.UniqueConstraint('reg_num')
    )
    op.create_table('warrant_receive_extends',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('receivable_id', sa.BigInteger(), nullable=False),
    sa.Column('receive_unit', sa.String(length=128), nullable=False, comment='应收单位名称'),
    sa.Column('created_by', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['receivable_id'], ['warrant_receivables.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('receivable_id', 'receive_unit', name='uq_receive_extend_unit')
    )
    op.create_index(op.f('ix_warrant_receive_extends_receivable_id'), 'warrant_receive_extends', ['receivable_id'], unique=False)
    op.create_table('warrant_softwares',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('other_id', sa.BigInteger(), nullable=False),
    sa.Column('software_name', sa.String(length=128), nullable=False),
    sa.Column('reg_num', sa.String(length=64), nullable=False),
    sa.Column('created_by', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['other_id'], ['warrant_others.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('other_id'),
    sa.UniqueConstraint('reg_num')
    )
    op.create_table('customer_directors',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('company_id', sa.BigInteger(), nullable=False),
    sa.Column('director_name', sa.String(length=128), nullable=False),
    sa.Column('ordery', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['customer_company_profiles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'director_name', name='uq_director')
    )
    op.create_index(op.f('ix_customer_directors_company_id'), 'customer_directors', ['company_id'], unique=False)
    op.create_table('customer_shareholders',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('company_id', sa.BigInteger(), nullable=False),
    sa.Column('shareholder_name', sa.String(length=128), nullable=False),
    sa.Column('invested_amount', sa.Numeric(precision=18, scale=2), nullable=True, comment='投资额'),
    sa.Column('shareholding_ratio', sa.Numeric(precision=8, scale=4), nullable=False, comment='持股比例%'),
    sa.ForeignKeyConstraint(['company_id'], ['customer_company_profiles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'shareholder_name', name='uq_shareholder')
    )
    op.create_index(op.f('ix_customer_shareholders_company_id'), 'customer_shareholders', ['company_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # MySQL 1553：FK 约束存在时不可先删其索引；禁用检查后统一 drop_table
    op.execute("SET FOREIGN_KEY_CHECKS = 0")
    op.drop_index(op.f('ix_customer_shareholders_company_id'), table_name='customer_shareholders')
    op.drop_table('customer_shareholders')
    op.drop_index(op.f('ix_customer_directors_company_id'), table_name='customer_directors')
    op.drop_table('customer_directors')
    op.drop_table('warrant_softwares')
    op.drop_index(op.f('ix_warrant_receive_extends_receivable_id'), table_name='warrant_receive_extends')
    op.drop_table('warrant_receive_extends')
    op.drop_table('warrant_patents')
    op.drop_index(op.f('ix_warrant_ownerships_warrant_id'), table_name='warrant_ownerships')
    op.drop_index(op.f('ix_warrant_ownerships_owner_id'), table_name='warrant_ownerships')
    op.drop_table('warrant_ownerships')
    op.drop_index(op.f('ix_warrant_evaluate_rechecks_evaluate_id'), table_name='warrant_evaluate_rechecks')
    op.drop_table('warrant_evaluate_rechecks')
    op.drop_index(op.f('ix_warrant_draft_extends_draft_state'), table_name='warrant_draft_extends')
    op.drop_index(op.f('ix_warrant_draft_extends_draft_id'), table_name='warrant_draft_extends')
    op.drop_index(op.f('ix_warrant_draft_extends_core_id'), table_name='warrant_draft_extends')
    op.drop_index(op.f('ix_warrant_draft_extends_acceptor_id'), table_name='warrant_draft_extends')
    op.drop_index('idx_draft_extend_num', table_name='warrant_draft_extends')
    op.drop_table('warrant_draft_extends')
    op.drop_index(op.f('ix_institution_credit_histories_institution_id'), table_name='institution_credit_histories')
    op.drop_table('institution_credit_histories')
    op.drop_index(op.f('ix_customer_personal_profiles_customer_id'), table_name='customer_personal_profiles')
    op.drop_table('customer_personal_profiles')
    op.drop_index(op.f('ix_customer_extends_customer_id'), table_name='customer_extends')
    op.drop_table('customer_extends')
    op.drop_index(op.f('ix_customer_core_limits_status'), table_name='customer_core_limits')
    op.drop_index(op.f('ix_customer_core_limits_customer_id'), table_name='customer_core_limits')
    op.drop_table('customer_core_limits')
    op.drop_index(op.f('ix_customer_core_histories_customer_id'), table_name='customer_core_histories')
    op.drop_table('customer_core_histories')
    op.drop_index(op.f('ix_customer_company_profiles_customer_id'), table_name='customer_company_profiles')
    op.drop_table('customer_company_profiles')
    op.drop_table('warrant_vehicles')
    op.drop_index(op.f('ix_warrant_storages_warrant_id'), table_name='warrant_storages')
    op.drop_table('warrant_storages')
    op.drop_table('warrant_stocks')
    op.drop_table('warrant_receivables')
    op.drop_table('warrant_others')
    op.drop_index(op.f('ix_warrant_houses_warrant_id'), table_name='warrant_houses')
    op.drop_table('warrant_houses')
    op.drop_table('warrant_grounds')
    op.drop_index(op.f('ix_warrant_evaluates_warrant_id'), table_name='warrant_evaluates')
    op.drop_table('warrant_evaluates')
    op.drop_table('warrant_drafts')
    op.drop_table('warrant_constructions')
    op.drop_table('warrant_chattels')
    op.drop_index(op.f('ix_institution_credit_agreements_status'), table_name='institution_credit_agreements')
    op.drop_index(op.f('ix_institution_credit_agreements_institution_id'), table_name='institution_credit_agreements')
    op.drop_index(op.f('ix_institution_credit_agreements_agreement_type'), table_name='institution_credit_agreements')
    op.drop_index('idx_agreement_inst_status_type', table_name='institution_credit_agreements')
    op.drop_table('institution_credit_agreements')
    op.drop_index(op.f('ix_institution_contacts_institution_id'), table_name='institution_contacts')
    op.drop_table('institution_contacts')
    op.drop_index(op.f('ix_institution_branches_status'), table_name='institution_branches')
    op.drop_index(op.f('ix_institution_branches_institution_id'), table_name='institution_branches')
    op.drop_table('institution_branches')
    op.drop_constraint('fk_group_parent_customer', 'customer_groups', type_='foreignkey')
    op.drop_index(op.f('ix_customers_region_id'), table_name='customers')
    op.drop_index(op.f('ix_customers_name'), table_name='customers')
    op.drop_index(op.f('ix_customers_managementor_id'), table_name='customers')
    op.drop_index(op.f('ix_customers_is_core'), table_name='customers')
    op.drop_index(op.f('ix_customers_is_acceptor'), table_name='customers')
    op.drop_index(op.f('ix_customers_group_id'), table_name='customers')
    op.drop_index(op.f('ix_customers_genre'), table_name='customers')
    op.drop_index(op.f('ix_customers_custom_state'), table_name='customers')
    op.drop_index(op.f('ix_customers_credit_region_id'), table_name='customers')
    op.drop_index(op.f('ix_customers_classification'), table_name='customers')
    op.drop_table('customers')
    op.drop_index(op.f('ix_approval_tasks_status'), table_name='approval_tasks')
    op.drop_index(op.f('ix_approval_tasks_instance_id'), table_name='approval_tasks')
    op.drop_index(op.f('ix_approval_tasks_approver_id'), table_name='approval_tasks')
    op.drop_index('idx_task_instance_step', table_name='approval_tasks')
    op.drop_table('approval_tasks')
    op.drop_index(op.f('ix_warrants_warrant_type'), table_name='warrants')
    op.drop_index(op.f('ix_warrants_warrant_state'), table_name='warrants')
    op.drop_index(op.f('ix_warrants_created_by'), table_name='warrants')
    op.drop_index(op.f('ix_warrants_auction_state'), table_name='warrants')
    op.drop_table('warrants')
    op.drop_table('warrant_evaluate_companies')
    op.drop_index(op.f('ix_institutions_status'), table_name='institutions')
    op.drop_index(op.f('ix_institutions_institution_type'), table_name='institutions')
    op.drop_table('institutions')
    op.drop_index(op.f('ix_customer_groups_parent_id'), table_name='customer_groups')
    op.drop_index(op.f('ix_customer_groups_parent_customer_id'), table_name='customer_groups')
    op.drop_table('customer_groups')
    op.drop_table('customer_extra_tags')
    op.drop_index(op.f('ix_customer_credit_regions_parent_id'), table_name='customer_credit_regions')
    op.drop_table('customer_credit_regions')
    op.drop_index(op.f('ix_attachments_uploaded_by'), table_name='attachments')
    op.drop_index('idx_attachment_resource', table_name='attachments')
    op.drop_table('attachments')
    op.drop_index(op.f('ix_approval_instances_submitted_by'), table_name='approval_instances')
    op.drop_index(op.f('ix_approval_instances_status'), table_name='approval_instances')
    op.drop_index(op.f('ix_approval_instances_flow_code'), table_name='approval_instances')
    op.drop_index(op.f('ix_approval_instances_biz_type'), table_name='approval_instances')
    op.drop_index(op.f('ix_approval_instances_biz_id'), table_name='approval_instances')
    op.drop_index('idx_inst_biz', table_name='approval_instances')
    op.drop_table('approval_instances')
    op.drop_index(op.f('ix_approval_flow_nodes_flow_def_id'), table_name='approval_flow_nodes')
    op.drop_index('idx_flow_node_def_step', table_name='approval_flow_nodes')
    op.drop_table('approval_flow_nodes')
    op.drop_index(op.f('ix_warrant_house_apps_parent_id'), table_name='warrant_house_apps')
    op.drop_table('warrant_house_apps')
    op.drop_index(op.f('ix_customer_regions_parent_id'), table_name='customer_regions')
    op.drop_table('customer_regions')
    op.drop_index(op.f('ix_customer_industries_parent_id'), table_name='customer_industries')
    op.drop_table('customer_industries')
    op.drop_index('idx_flow_def_code', table_name='approval_flow_defs')
    op.drop_table('approval_flow_defs')
    op.execute("SET FOREIGN_KEY_CHECKS = 1")
    # ### end Alembic commands ###
