"""article_product_category

Revision ID: 8f84a6f42726
Revises: 0212709b1d34
Create Date: 2026-09-10 17:00:31.008752

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '8f84a6f42726'
down_revision: Union[str, None] = '0212709b1d34'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article_products', sa.Column('category', sa.SmallInteger(), nullable=False, comment='产品类别'))
    op.drop_column('article_products', 'difficulty_score')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article_products', sa.Column('difficulty_score', mysql.DECIMAL(precision=6, scale=2), nullable=False, comment='难度系数'))
    op.drop_column('article_products', 'category')
    # ### end Alembic commands ###
