"""drop_custom_typ_is_core_is_acceptor

Revision ID: ad9af5bd88d8
Revises: 0a0c1e2e4d5f
Create Date: 2026-09-01 10:30:34.537575

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'ad9af5bd88d8'
down_revision: Union[str, None] = '0a0c1e2e4d5f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customers', 'custom_typ')
    op.drop_column('customers', 'is_acceptor')
    op.drop_column('customers', 'is_core')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('is_core', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False, comment='票据核心企业'))
    op.add_column('customers', sa.Column('is_acceptor', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False, comment='票据承兑人'))
    op.add_column('customers', sa.Column('custom_typ', mysql.SMALLINT(), autoincrement=False, nullable=False, comment='10新增20存量30存量新增'))
    # ### end Alembic commands ###
