"""group_credit_region_parent_id_null

Revision ID: d908b63105e9
Revises: b3a07d2c91e4
Create Date: 2026-08-29 22:46:37.576030

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'd908b63105e9'
down_revision: Union[str, None] = 'b3a07d2c91e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('customer_credit_regions', 'parent_id',
               existing_type=mysql.BIGINT(),
               nullable=True,
               comment='上级区域，NULL=顶级')
    op.alter_column('customer_groups', 'parent_id',
               existing_type=mysql.BIGINT(),
               nullable=True,
               comment='上级集团，NULL=顶级')
    # ### end Alembic commands ###
    # 数据迁移：原 0=顶级 统一改为 NULL（与 parent_customer_id 的"无值"表示对齐）
    op.execute("UPDATE customer_credit_regions SET parent_id = NULL WHERE parent_id = 0")
    op.execute("UPDATE customer_groups SET parent_id = NULL WHERE parent_id = 0")


def downgrade() -> None:
    # 逆数据迁移：NULL 还原为 0，再收回 NOT NULL
    op.execute("UPDATE customer_credit_regions SET parent_id = 0 WHERE parent_id IS NULL")
    op.execute("UPDATE customer_groups SET parent_id = 0 WHERE parent_id IS NULL")
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('customer_groups', 'parent_id',
               existing_type=mysql.BIGINT(),
               nullable=False,
               comment=None,
               existing_comment='上级集团，NULL=顶级')
    op.alter_column('customer_credit_regions', 'parent_id',
               existing_type=mysql.BIGINT(),
               nullable=False,
               comment=None,
               existing_comment='上级区域，NULL=顶级')
    # ### end Alembic commands ###
