"""approval_task_stage

Revision ID: dc5399375112
Revises: 0e9880fcaf6d
Create Date: 2026-09-10 18:05:13.559371

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'dc5399375112'
down_revision: Union[str, None] = '0e9880fcaf6d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('approval_tasks', sa.Column('stage', sa.SmallInteger(), nullable=False, comment='对应节点 stage'))
    op.alter_column('approval_tasks', 'step',
               existing_type=mysql.SMALLINT(),
               comment='对应节点 step（stage 内部序号）',
               existing_comment='对应节点 step',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('approval_tasks', 'step',
               existing_type=mysql.SMALLINT(),
               comment='对应节点 step',
               existing_comment='对应节点 step（stage 内部序号）',
               existing_nullable=False)
    op.drop_column('approval_tasks', 'stage')
    # ### end Alembic commands ###
